
sudo: required
services:
    - docker

before_install:
    - docker build -t ronaldcast/react-test -f ./client/Dockerfile.dev ./client/.

script:
    - docker run -e CI=true ronaldcast/react-test npm run test

after_success:
    - docker build -t ronaldcast/multi-client ./client/.
    - docker build -t ronaldcast/multi-nginx ./nginx/.
    - docker build -t ronaldcast/multi-server ./server/.
    - docker build -t ronaldcast/multi-worker ./worker/.
    # Log in to the docker CLI
    - echo  "$DOCKER_PASSWORD" |  docker login -u "$DOCKER_ID" --password-stdin
    #take those images and push them to docker hub
    - docker push ronaldcast/multi-client 
    - docker push ronaldcast/multi-nginx 
    - docker push ronaldcast/multi-server 
    - docker push ronaldcast/multi-worker 

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-024792341253"
    bucket_path: "docker-multi"
    on:
        branch: master 
    access_key_id: $AWS_ACCESS_KEY      
    secret_access_key: $AWS_SECRET_KEY

