version: '3'
services: 
    postgres:
        image: 'postgres:latest'
        environment: 
            - POSTGRES_PASSWORD=postgres_password  
            - POSTGRES_DB=postgres
    redis: 
        image: 'redis:latest'
    nginx:
        depends_on:
            - server #representa las imagenes de las culaes depende y de esta manera dichar imagenes corren primero 
            - client
        restart: always
        build: 
            dockerfile: Dockerfile.dev 
            context: ./nginx
        ports: 
          - '3050:80'

    server:
        depends_on: #
            - postgres
        build:
            dockerfile: Dockerfile.dev
            context: ./server  #server directory
        volumes:  #refletion of change
            - /app/node_modules 
            - ./server:/app    
        environment: 
            - REDIS_HOST=redis #el nombre del server redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    client:   
        stdin_open: true
        build: 
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /app/node_modules
            - ./client:/app
    worker:
        build: 
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes: 
            - /app/node_modules
            - ./worker:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379       


